### ISSUE TITLE
mars_package paths are wrong

### ISSUE THREAD

**Issue by saarnold** [envire/package_set#1]
Since we have this mars_package method in the envire package set the update fails. 
For the line `mars_package("simulation/mars/plugins/envire_graphics")` he tries to pick up the repository in `github.com:/envire/simulation-envire_graphics.git` which does not exist.
@Rauldg what was the intention here?

**Comment by Rauldg** [comment]
I would like to have these two mars plugins (envire_physics and envire_graphics) recognized by autoproj. I looked to similar cases and this was the way it was done.

This is not triggering any error in my system... I don't know why it does in others. I am on the branch envire of buildconf maybe something is different there?

**Comment by saarnold** [comment]
As far as I can see the envire package set is not picked up in the entern buildconf and also not on the envire branch. So this error only occurs when using the envire buildconf.

**Comment by Rauldg** [comment]
Envire package set should be picked in the envire branch of the entern buildconf. Unless I am missing something:
https://git.hb.dfki.de/entern/buildconf/blob/envire/manifest

I am not using the envire buildconf but the entern buildconf on branch envire.

**Comment by Rauldg** [comment]
I will close this issue, until the features from envire-mars get merged with mars, the only way to have access to those features implies setting the package set to a version previous to the removal of the mentioned mars_package declarations.
